export const FORM_WRAPPER_COL_OFFSET = 4
export const FORM_WRAPPER_COL_SPAN = 20

export const DEFAULT_PAGE_WIDHT = 375
export const DEFAULT_PAGE_HEIGHT = 560
export const DEFAULT_RATIO = DEFAULT_PAGE_HEIGHT / DEFAULT_PAGE_WIDHT